#!/bin/bash

if [ $# -ne 4 ]; then
  echo "usage: $0 nsamples output_file lightFile heavyFile"
  exit 1
fi

# read arguments
num=$1
outputFile=$2
lightFile=$3
heavyFile=$4

# run the OSCAR to UrQMD converter
# ftn10 would be light hadron sampled from particlization
# ftn20 would be Dmeson sampled from fragPLUSrecomb
# nsamples would be # of oversamples from hypersurface
export ftn20=$heavyFile
./osc2u < $lightFile nsamples=$num > urqmd_input.dat || exit 1

# create UrQMD config file
cat > urqmd.conf <<EOF
# calculate until a late time
# output only the final timestep
tim 8000 8000

# read initial state from file 10
cto 40 2

# write to file 30, suppress all others
f13
f14
f15
f16
f18
f19
f20
#f30

# end of file
xxx
EOF

# run UrQMD
ftn09=urqmd.conf ftn10=urqmd_input.dat ftn30=$outputFile ./urqmd || exit 1
